/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as HonaiImport } from './routes/honai'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as IndexImport } from './routes/index'
import { Route as HonaiIndexImport } from './routes/honai/index'
import { Route as HonaiAccountRouteImport } from './routes/honai/account/route'
import { Route as HonaiTrxNewSalesIndexImport } from './routes/honai/trx-new-sales/index'
import { Route as HonaiRevenueRedeemPvIndexImport } from './routes/honai/revenue-redeem-pv/index'
import { Route as HonaiRevenueNewSalesIndexImport } from './routes/honai/revenue-new-sales/index'
import { Route as HonaiRevenueNewSalesPrabayarIndexImport } from './routes/honai/revenue-new-sales-prabayar/index'
import { Route as HonaiRevenueGrossIndexImport } from './routes/honai/revenue-gross/index'
import { Route as HonaiRevenueGrossPrabayarIndexImport } from './routes/honai/revenue-gross-prabayar/index'
import { Route as HonaiRevenueCvmIndexImport } from './routes/honai/revenue-cvm/index'
import { Route as HonaiAccountIndexImport } from './routes/honai/account/index'
import { Route as HonaiAccountPasswordImport } from './routes/honai/account/password'
import { Route as HonaiAccountAppearanceImport } from './routes/honai/account/appearance'
import { Route as HonaiFmcLineInServiceIndexImport } from './routes/honai/fmc/line-in-service/index'
import { Route as HonaiFmcConnectWifiIndexImport } from './routes/honai/fmc/connect-wifi/index'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const HonaiRoute = HonaiImport.update({
  id: '/honai',
  path: '/honai',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const HonaiIndexRoute = HonaiIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HonaiRoute,
} as any)

const HonaiAccountRouteRoute = HonaiAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => HonaiRoute,
} as any)

const HonaiTrxNewSalesIndexRoute = HonaiTrxNewSalesIndexImport.update({
  id: '/trx-new-sales/',
  path: '/trx-new-sales/',
  getParentRoute: () => HonaiRoute,
} as any)

const HonaiRevenueRedeemPvIndexRoute = HonaiRevenueRedeemPvIndexImport.update({
  id: '/revenue-redeem-pv/',
  path: '/revenue-redeem-pv/',
  getParentRoute: () => HonaiRoute,
} as any)

const HonaiRevenueNewSalesIndexRoute = HonaiRevenueNewSalesIndexImport.update({
  id: '/revenue-new-sales/',
  path: '/revenue-new-sales/',
  getParentRoute: () => HonaiRoute,
} as any)

const HonaiRevenueNewSalesPrabayarIndexRoute =
  HonaiRevenueNewSalesPrabayarIndexImport.update({
    id: '/revenue-new-sales-prabayar/',
    path: '/revenue-new-sales-prabayar/',
    getParentRoute: () => HonaiRoute,
  } as any)

const HonaiRevenueGrossIndexRoute = HonaiRevenueGrossIndexImport.update({
  id: '/revenue-gross/',
  path: '/revenue-gross/',
  getParentRoute: () => HonaiRoute,
} as any)

const HonaiRevenueGrossPrabayarIndexRoute =
  HonaiRevenueGrossPrabayarIndexImport.update({
    id: '/revenue-gross-prabayar/',
    path: '/revenue-gross-prabayar/',
    getParentRoute: () => HonaiRoute,
  } as any)

const HonaiRevenueCvmIndexRoute = HonaiRevenueCvmIndexImport.update({
  id: '/revenue-cvm/',
  path: '/revenue-cvm/',
  getParentRoute: () => HonaiRoute,
} as any)

const HonaiAccountIndexRoute = HonaiAccountIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HonaiAccountRouteRoute,
} as any)

const HonaiAccountPasswordRoute = HonaiAccountPasswordImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => HonaiAccountRouteRoute,
} as any)

const HonaiAccountAppearanceRoute = HonaiAccountAppearanceImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => HonaiAccountRouteRoute,
} as any)

const HonaiFmcLineInServiceIndexRoute = HonaiFmcLineInServiceIndexImport.update(
  {
    id: '/fmc/line-in-service/',
    path: '/fmc/line-in-service/',
    getParentRoute: () => HonaiRoute,
  } as any,
)

const HonaiFmcConnectWifiIndexRoute = HonaiFmcConnectWifiIndexImport.update({
  id: '/fmc/connect-wifi/',
  path: '/fmc/connect-wifi/',
  getParentRoute: () => HonaiRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/honai': {
      id: '/honai'
      path: '/honai'
      fullPath: '/honai'
      preLoaderRoute: typeof HonaiImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/honai/account': {
      id: '/honai/account'
      path: '/account'
      fullPath: '/honai/account'
      preLoaderRoute: typeof HonaiAccountRouteImport
      parentRoute: typeof HonaiImport
    }
    '/honai/': {
      id: '/honai/'
      path: '/'
      fullPath: '/honai/'
      preLoaderRoute: typeof HonaiIndexImport
      parentRoute: typeof HonaiImport
    }
    '/honai/account/appearance': {
      id: '/honai/account/appearance'
      path: '/appearance'
      fullPath: '/honai/account/appearance'
      preLoaderRoute: typeof HonaiAccountAppearanceImport
      parentRoute: typeof HonaiAccountRouteImport
    }
    '/honai/account/password': {
      id: '/honai/account/password'
      path: '/password'
      fullPath: '/honai/account/password'
      preLoaderRoute: typeof HonaiAccountPasswordImport
      parentRoute: typeof HonaiAccountRouteImport
    }
    '/honai/account/': {
      id: '/honai/account/'
      path: '/'
      fullPath: '/honai/account/'
      preLoaderRoute: typeof HonaiAccountIndexImport
      parentRoute: typeof HonaiAccountRouteImport
    }
    '/honai/revenue-cvm/': {
      id: '/honai/revenue-cvm/'
      path: '/revenue-cvm'
      fullPath: '/honai/revenue-cvm'
      preLoaderRoute: typeof HonaiRevenueCvmIndexImport
      parentRoute: typeof HonaiImport
    }
    '/honai/revenue-gross-prabayar/': {
      id: '/honai/revenue-gross-prabayar/'
      path: '/revenue-gross-prabayar'
      fullPath: '/honai/revenue-gross-prabayar'
      preLoaderRoute: typeof HonaiRevenueGrossPrabayarIndexImport
      parentRoute: typeof HonaiImport
    }
    '/honai/revenue-gross/': {
      id: '/honai/revenue-gross/'
      path: '/revenue-gross'
      fullPath: '/honai/revenue-gross'
      preLoaderRoute: typeof HonaiRevenueGrossIndexImport
      parentRoute: typeof HonaiImport
    }
    '/honai/revenue-new-sales-prabayar/': {
      id: '/honai/revenue-new-sales-prabayar/'
      path: '/revenue-new-sales-prabayar'
      fullPath: '/honai/revenue-new-sales-prabayar'
      preLoaderRoute: typeof HonaiRevenueNewSalesPrabayarIndexImport
      parentRoute: typeof HonaiImport
    }
    '/honai/revenue-new-sales/': {
      id: '/honai/revenue-new-sales/'
      path: '/revenue-new-sales'
      fullPath: '/honai/revenue-new-sales'
      preLoaderRoute: typeof HonaiRevenueNewSalesIndexImport
      parentRoute: typeof HonaiImport
    }
    '/honai/revenue-redeem-pv/': {
      id: '/honai/revenue-redeem-pv/'
      path: '/revenue-redeem-pv'
      fullPath: '/honai/revenue-redeem-pv'
      preLoaderRoute: typeof HonaiRevenueRedeemPvIndexImport
      parentRoute: typeof HonaiImport
    }
    '/honai/trx-new-sales/': {
      id: '/honai/trx-new-sales/'
      path: '/trx-new-sales'
      fullPath: '/honai/trx-new-sales'
      preLoaderRoute: typeof HonaiTrxNewSalesIndexImport
      parentRoute: typeof HonaiImport
    }
    '/honai/fmc/connect-wifi/': {
      id: '/honai/fmc/connect-wifi/'
      path: '/fmc/connect-wifi'
      fullPath: '/honai/fmc/connect-wifi'
      preLoaderRoute: typeof HonaiFmcConnectWifiIndexImport
      parentRoute: typeof HonaiImport
    }
    '/honai/fmc/line-in-service/': {
      id: '/honai/fmc/line-in-service/'
      path: '/fmc/line-in-service'
      fullPath: '/honai/fmc/line-in-service'
      preLoaderRoute: typeof HonaiFmcLineInServiceIndexImport
      parentRoute: typeof HonaiImport
    }
  }
}

// Create and export the route tree

interface HonaiAccountRouteRouteChildren {
  HonaiAccountAppearanceRoute: typeof HonaiAccountAppearanceRoute
  HonaiAccountPasswordRoute: typeof HonaiAccountPasswordRoute
  HonaiAccountIndexRoute: typeof HonaiAccountIndexRoute
}

const HonaiAccountRouteRouteChildren: HonaiAccountRouteRouteChildren = {
  HonaiAccountAppearanceRoute: HonaiAccountAppearanceRoute,
  HonaiAccountPasswordRoute: HonaiAccountPasswordRoute,
  HonaiAccountIndexRoute: HonaiAccountIndexRoute,
}

const HonaiAccountRouteRouteWithChildren =
  HonaiAccountRouteRoute._addFileChildren(HonaiAccountRouteRouteChildren)

interface HonaiRouteChildren {
  HonaiAccountRouteRoute: typeof HonaiAccountRouteRouteWithChildren
  HonaiIndexRoute: typeof HonaiIndexRoute
  HonaiRevenueCvmIndexRoute: typeof HonaiRevenueCvmIndexRoute
  HonaiRevenueGrossPrabayarIndexRoute: typeof HonaiRevenueGrossPrabayarIndexRoute
  HonaiRevenueGrossIndexRoute: typeof HonaiRevenueGrossIndexRoute
  HonaiRevenueNewSalesPrabayarIndexRoute: typeof HonaiRevenueNewSalesPrabayarIndexRoute
  HonaiRevenueNewSalesIndexRoute: typeof HonaiRevenueNewSalesIndexRoute
  HonaiRevenueRedeemPvIndexRoute: typeof HonaiRevenueRedeemPvIndexRoute
  HonaiTrxNewSalesIndexRoute: typeof HonaiTrxNewSalesIndexRoute
  HonaiFmcConnectWifiIndexRoute: typeof HonaiFmcConnectWifiIndexRoute
  HonaiFmcLineInServiceIndexRoute: typeof HonaiFmcLineInServiceIndexRoute
}

const HonaiRouteChildren: HonaiRouteChildren = {
  HonaiAccountRouteRoute: HonaiAccountRouteRouteWithChildren,
  HonaiIndexRoute: HonaiIndexRoute,
  HonaiRevenueCvmIndexRoute: HonaiRevenueCvmIndexRoute,
  HonaiRevenueGrossPrabayarIndexRoute: HonaiRevenueGrossPrabayarIndexRoute,
  HonaiRevenueGrossIndexRoute: HonaiRevenueGrossIndexRoute,
  HonaiRevenueNewSalesPrabayarIndexRoute:
    HonaiRevenueNewSalesPrabayarIndexRoute,
  HonaiRevenueNewSalesIndexRoute: HonaiRevenueNewSalesIndexRoute,
  HonaiRevenueRedeemPvIndexRoute: HonaiRevenueRedeemPvIndexRoute,
  HonaiTrxNewSalesIndexRoute: HonaiTrxNewSalesIndexRoute,
  HonaiFmcConnectWifiIndexRoute: HonaiFmcConnectWifiIndexRoute,
  HonaiFmcLineInServiceIndexRoute: HonaiFmcLineInServiceIndexRoute,
}

const HonaiRouteWithChildren = HonaiRoute._addFileChildren(HonaiRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/honai': typeof HonaiRouteWithChildren
  '/login': typeof LoginRoute
  '/honai/account': typeof HonaiAccountRouteRouteWithChildren
  '/honai/': typeof HonaiIndexRoute
  '/honai/account/appearance': typeof HonaiAccountAppearanceRoute
  '/honai/account/password': typeof HonaiAccountPasswordRoute
  '/honai/account/': typeof HonaiAccountIndexRoute
  '/honai/revenue-cvm': typeof HonaiRevenueCvmIndexRoute
  '/honai/revenue-gross-prabayar': typeof HonaiRevenueGrossPrabayarIndexRoute
  '/honai/revenue-gross': typeof HonaiRevenueGrossIndexRoute
  '/honai/revenue-new-sales-prabayar': typeof HonaiRevenueNewSalesPrabayarIndexRoute
  '/honai/revenue-new-sales': typeof HonaiRevenueNewSalesIndexRoute
  '/honai/revenue-redeem-pv': typeof HonaiRevenueRedeemPvIndexRoute
  '/honai/trx-new-sales': typeof HonaiTrxNewSalesIndexRoute
  '/honai/fmc/connect-wifi': typeof HonaiFmcConnectWifiIndexRoute
  '/honai/fmc/line-in-service': typeof HonaiFmcLineInServiceIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/honai': typeof HonaiIndexRoute
  '/honai/account/appearance': typeof HonaiAccountAppearanceRoute
  '/honai/account/password': typeof HonaiAccountPasswordRoute
  '/honai/account': typeof HonaiAccountIndexRoute
  '/honai/revenue-cvm': typeof HonaiRevenueCvmIndexRoute
  '/honai/revenue-gross-prabayar': typeof HonaiRevenueGrossPrabayarIndexRoute
  '/honai/revenue-gross': typeof HonaiRevenueGrossIndexRoute
  '/honai/revenue-new-sales-prabayar': typeof HonaiRevenueNewSalesPrabayarIndexRoute
  '/honai/revenue-new-sales': typeof HonaiRevenueNewSalesIndexRoute
  '/honai/revenue-redeem-pv': typeof HonaiRevenueRedeemPvIndexRoute
  '/honai/trx-new-sales': typeof HonaiTrxNewSalesIndexRoute
  '/honai/fmc/connect-wifi': typeof HonaiFmcConnectWifiIndexRoute
  '/honai/fmc/line-in-service': typeof HonaiFmcLineInServiceIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/honai': typeof HonaiRouteWithChildren
  '/login': typeof LoginRoute
  '/honai/account': typeof HonaiAccountRouteRouteWithChildren
  '/honai/': typeof HonaiIndexRoute
  '/honai/account/appearance': typeof HonaiAccountAppearanceRoute
  '/honai/account/password': typeof HonaiAccountPasswordRoute
  '/honai/account/': typeof HonaiAccountIndexRoute
  '/honai/revenue-cvm/': typeof HonaiRevenueCvmIndexRoute
  '/honai/revenue-gross-prabayar/': typeof HonaiRevenueGrossPrabayarIndexRoute
  '/honai/revenue-gross/': typeof HonaiRevenueGrossIndexRoute
  '/honai/revenue-new-sales-prabayar/': typeof HonaiRevenueNewSalesPrabayarIndexRoute
  '/honai/revenue-new-sales/': typeof HonaiRevenueNewSalesIndexRoute
  '/honai/revenue-redeem-pv/': typeof HonaiRevenueRedeemPvIndexRoute
  '/honai/trx-new-sales/': typeof HonaiTrxNewSalesIndexRoute
  '/honai/fmc/connect-wifi/': typeof HonaiFmcConnectWifiIndexRoute
  '/honai/fmc/line-in-service/': typeof HonaiFmcLineInServiceIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/honai'
    | '/login'
    | '/honai/account'
    | '/honai/'
    | '/honai/account/appearance'
    | '/honai/account/password'
    | '/honai/account/'
    | '/honai/revenue-cvm'
    | '/honai/revenue-gross-prabayar'
    | '/honai/revenue-gross'
    | '/honai/revenue-new-sales-prabayar'
    | '/honai/revenue-new-sales'
    | '/honai/revenue-redeem-pv'
    | '/honai/trx-new-sales'
    | '/honai/fmc/connect-wifi'
    | '/honai/fmc/line-in-service'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/honai'
    | '/honai/account/appearance'
    | '/honai/account/password'
    | '/honai/account'
    | '/honai/revenue-cvm'
    | '/honai/revenue-gross-prabayar'
    | '/honai/revenue-gross'
    | '/honai/revenue-new-sales-prabayar'
    | '/honai/revenue-new-sales'
    | '/honai/revenue-redeem-pv'
    | '/honai/trx-new-sales'
    | '/honai/fmc/connect-wifi'
    | '/honai/fmc/line-in-service'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/honai'
    | '/login'
    | '/honai/account'
    | '/honai/'
    | '/honai/account/appearance'
    | '/honai/account/password'
    | '/honai/account/'
    | '/honai/revenue-cvm/'
    | '/honai/revenue-gross-prabayar/'
    | '/honai/revenue-gross/'
    | '/honai/revenue-new-sales-prabayar/'
    | '/honai/revenue-new-sales/'
    | '/honai/revenue-redeem-pv/'
    | '/honai/trx-new-sales/'
    | '/honai/fmc/connect-wifi/'
    | '/honai/fmc/line-in-service/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  HonaiRoute: typeof HonaiRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  HonaiRoute: HonaiRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard",
        "/honai",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/honai": {
      "filePath": "honai.tsx",
      "children": [
        "/honai/account",
        "/honai/",
        "/honai/revenue-cvm/",
        "/honai/revenue-gross-prabayar/",
        "/honai/revenue-gross/",
        "/honai/revenue-new-sales-prabayar/",
        "/honai/revenue-new-sales/",
        "/honai/revenue-redeem-pv/",
        "/honai/trx-new-sales/",
        "/honai/fmc/connect-wifi/",
        "/honai/fmc/line-in-service/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/honai/account": {
      "filePath": "honai/account/route.tsx",
      "parent": "/honai",
      "children": [
        "/honai/account/appearance",
        "/honai/account/password",
        "/honai/account/"
      ]
    },
    "/honai/": {
      "filePath": "honai/index.tsx",
      "parent": "/honai"
    },
    "/honai/account/appearance": {
      "filePath": "honai/account/appearance.tsx",
      "parent": "/honai/account"
    },
    "/honai/account/password": {
      "filePath": "honai/account/password.tsx",
      "parent": "/honai/account"
    },
    "/honai/account/": {
      "filePath": "honai/account/index.tsx",
      "parent": "/honai/account"
    },
    "/honai/revenue-cvm/": {
      "filePath": "honai/revenue-cvm/index.tsx",
      "parent": "/honai"
    },
    "/honai/revenue-gross-prabayar/": {
      "filePath": "honai/revenue-gross-prabayar/index.tsx",
      "parent": "/honai"
    },
    "/honai/revenue-gross/": {
      "filePath": "honai/revenue-gross/index.tsx",
      "parent": "/honai"
    },
    "/honai/revenue-new-sales-prabayar/": {
      "filePath": "honai/revenue-new-sales-prabayar/index.tsx",
      "parent": "/honai"
    },
    "/honai/revenue-new-sales/": {
      "filePath": "honai/revenue-new-sales/index.tsx",
      "parent": "/honai"
    },
    "/honai/revenue-redeem-pv/": {
      "filePath": "honai/revenue-redeem-pv/index.tsx",
      "parent": "/honai"
    },
    "/honai/trx-new-sales/": {
      "filePath": "honai/trx-new-sales/index.tsx",
      "parent": "/honai"
    },
    "/honai/fmc/connect-wifi/": {
      "filePath": "honai/fmc/connect-wifi/index.tsx",
      "parent": "/honai"
    },
    "/honai/fmc/line-in-service/": {
      "filePath": "honai/fmc/line-in-service/index.tsx",
      "parent": "/honai"
    }
  }
}
ROUTE_MANIFEST_END */
